"""Yahoo-Symbole zum Testen. Die Listen sind Näherungen an die Indizes des Planspiels (heutige Mitglieder, ohne Gewähr);
Symbole ohne Daten werden beim Laden übersprungen."""

DAX = ("SAP.DE SIE.DE ALV.DE DTE.DE AIR.DE MUV2.DE DBK.DE BAS.DE BMW.DE MBG.DE VOW3.DE ADS.DE IFX.DE RWE.DE EOAN.DE "
       "HEI.DE BAYN.DE DHL.DE DB1.DE FRE.DE MRK.DE SHL.DE SY1.DE ZAL.DE CBK.DE HNR1.DE BEI.DE CON.DE PAH3.DE QIA.DE "
       "RHM.DE MTX.DE ENR.DE VNA.DE 1COV.DE P911.DE DTG.DE BNR.DE HEN3.DE SRT3.DE").split()

MDAX = ("1U1.DE AFX.DE AG1.DE BC8.DE BOSS.DE EVD.DE EVK.DE FIE.DE FNTN.DE FPE3.DE G1A.DE GBF.DE GXI.DE HAG.DE HOT.DE JUN3.DE "
        "KBX.DE KGX.DE LEG.DE LHA.DE LXS.DE NDX1.DE NEM.DE PSM.DE PUM.DE RAA.DE RHK.DE SDF.DE SGL.DE SHA.DE SIX2.DE SZG.DE "
        "TKA.DE TLX.DE TUI1.DE UTDI.DE WCH.DE WAF.DE AT1.DE DUE.DE HFG.DE NDA.DE O2D.DE TEG.DE VBK.DE BNR.DE GYC.DE "
        "DWS.DE ARL.DE COK.DE EUZ.DE SAX.DE STM.DE TAG.DE WUW.DE ADV.DE PBB.DE DHER.DE").split()

EUROPE = ("ASML.AS HEIA.AS INGA.AS PHIA.AS AD.AS MC.PA OR.PA SAN.PA AI.PA SU.PA BNP.PA TTE.PA SAF.PA RMS.PA KER.PA CS.PA "
          "DG.PA GLE.PA ACA.PA EL.PA CAP.PA VIE.PA ML.PA ENEL.MI ENI.MI ISP.MI UCG.MI G.MI RACE.MI IBE.MC ITX.MC SAN.MC "
          "BBVA.MC REP.MC TEF.MC NOKIA.HE KNEBV.HE ABI.BR UCB.BR SOLB.BR EBS.VI VOE.VI OMV.VI ERG.MI PRY.MI STLAM.MI MB.MI").split()

US = ("AAPL MSFT AMZN GOOGL META NVDA AVGO COST NFLX ADBE PEP CSCO TMUS AMD INTC QCOM TXN AMGN HON SBUX INTU AMAT ISRG "
      "BKNG GILD MDLZ ADP LRCX REGN MU JPM V UNH JNJ WMT PG HD CVX KO MRK MCD DIS IBM CAT GS AXP MMM BA NKE CRM TRV VZ "
      "XOM PFE ORCL ABT TMO LLY MA BAC WFC C T CMCSA COP SLB LOW TGT UPS FDX GE LMT RTX DE EMR").split()

GROUPS = {"dax": DAX, "mdax": MDAX, "europa": EUROPE, "us": US}
ALL = [s for g in GROUPS.values() for s in g]
